#!/usr/bin/env bash
find src -type f \( -not -name '*.tsx' -and -not -name '*.ts' \) -exec sh -c '
  mkdir -p "$(
    dirname "dist/$(echo $1 | sed -e s#^src/##)"
  )"
  cp $1 "dist/$(echo $1 | sed -e s#^src/##)"
' shell {} \;
